-- DevOptimizeBot database schema
-- Run in the Supabase SQL Editor, or `supabase db push` as a migration.
-- After this, run seed_tools.sql (generated by scripts/generate_catalog.py)
-- to populate categories + tools.
--
-- NOTE ON PROVENANCE: the spec this schema was built from referenced "the
-- previous specification" for database architecture, which wasn't included.
-- Table names below match the spec exactly; column-level design (types,
-- constraints, RLS) was designed fresh here — adjust freely if your actual
-- prior schema differs.

create extension if not exists "uuid-ossp";

-- ============================================================================
-- TABLES
-- ============================================================================

create table if not exists public.users (
  id uuid primary key default uuid_generate_v4(),
  telegram_id bigint unique not null,
  telegram_username text,
  first_name text,
  last_name text,
  photo_url text,
  points_balance integer not null default 0 check (points_balance >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.categories (
  id serial primary key,
  slug text unique not null,
  name text not null,
  sort_order integer not null default 0
);

create table if not exists public.tools (
  id uuid primary key default uuid_generate_v4(),
  slug text unique not null,
  name text not null,
  category_id integer not null references public.categories(id) on delete restrict,
  description text,
  route_path text not null,
  is_enabled boolean not null default false,
  is_implemented boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.tool_usage (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references public.users(id) on delete set null,
  tool_id uuid references public.tools(id) on delete cascade,
  used_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.reward_events (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.users(id) on delete cascade,
  type text not null default 'rewarded_ad',
  status text not null default 'pending' check (status in ('pending', 'verified', 'rejected')),
  points_awarded integer not null default 0,
  monetag_event_id text,
  created_at timestamptz not null default now(),
  verified_at timestamptz
);

create table if not exists public.points_transactions (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.users(id) on delete cascade,
  delta integer not null,
  balance_after integer not null,
  reason text not null,
  reference_type text,
  reference_id uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.monetag_events (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references public.users(id) on delete set null,
  zone_id text,
  event_type text,
  raw_payload jsonb,
  verified boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.api_usage (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references public.users(id) on delete set null,
  tool_id uuid references public.tools(id) on delete set null,
  endpoint text not null,
  request_count integer not null default 1,
  window_start timestamptz not null default date_trunc('hour', now()),
  created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  id uuid primary key default uuid_generate_v4(),
  telegram_id bigint unique,
  email text unique,
  role text not null default 'admin',
  created_at timestamptz not null default now(),
  constraint admin_users_identity_present check (telegram_id is not null or email is not null)
);

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create index if not exists idx_tool_usage_user on public.tool_usage(user_id);
create index if not exists idx_tool_usage_tool on public.tool_usage(tool_id);
create index if not exists idx_points_transactions_user on public.points_transactions(user_id);
create index if not exists idx_reward_events_user on public.reward_events(user_id);
create index if not exists idx_tools_category on public.tools(category_id);

-- ============================================================================
-- ADMIN CHECK — used by RLS policies below and by the admin dashboard to
-- decide whether to show itself at all. Returns a boolean only; never
-- exposes the admin_users table's contents to a non-admin caller.
-- ============================================================================

create or replace function public.is_admin() returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users a
    join public.users u on u.telegram_id = a.telegram_id
    where u.id = auth.uid()
  );
$$;

grant execute on function public.is_admin() to authenticated;

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================

alter table public.users enable row level security;
alter table public.categories enable row level security;
alter table public.tools enable row level security;
alter table public.tool_usage enable row level security;
alter table public.reward_events enable row level security;
alter table public.points_transactions enable row level security;
alter table public.monetag_events enable row level security;
alter table public.api_usage enable row level security;
alter table public.admin_users enable row level security;
alter table public.app_settings enable row level security;

-- Catalog data is public read (the whole point of the homepage grid).
create policy "categories are publicly readable" on public.categories
  for select using (true);
create policy "tools are publicly readable" on public.tools
  for select using (true);

-- Users can see only their own row. There is deliberately no update/insert/
-- delete policy for the authenticated/anon roles on `users` — the row is
-- created by the telegram-auth Edge Function (service role) on first login,
-- and points_balance changes only via award_points() below.
create policy "users can view own row" on public.users
  for select using (auth.uid() = id);

create policy "users can view own usage" on public.tool_usage
  for select using (auth.uid() = user_id);
create policy "users can log own usage" on public.tool_usage
  for insert with check (auth.uid() = user_id);

create policy "users can view own reward events" on public.reward_events
  for select using (auth.uid() = user_id);
-- No insert policy for reward_events on authenticated/anon: rows are created
-- by the claim-ad-reward Edge Function (service role) so a client can't
-- fabricate a "verified" reward for itself.

create policy "users can view own points transactions" on public.points_transactions
  for select using (auth.uid() = user_id);
-- No insert/update/delete policy for points_transactions on authenticated/
-- anon at all — every row is written by award_points() below.

-- Admin dashboard: same tables, but readable in full by anyone is_admin()
-- says yes for. Ordinary users still only see their own rows via the
-- policies above — Postgres OR's every matching policy together, so an
-- admin satisfies BOTH "own row" and "is admin" and sees everything, while
-- a non-admin only ever satisfies the "own row" policy.
create policy "admins can view all users" on public.users
  for select using (public.is_admin());
create policy "admins can view all tool usage" on public.tool_usage
  for select using (public.is_admin());
create policy "admins can view all reward events" on public.reward_events
  for select using (public.is_admin());
create policy "admins can view all points transactions" on public.points_transactions
  for select using (public.is_admin());

-- admin_users itself: admins can see who the other admins are, nobody else
-- can see this table at all (not even non-admin authenticated users).
create policy "admins can view admin list" on public.admin_users
  for select using (public.is_admin());

-- app_settings: publicly readable is unnecessary (nothing in the public UI
-- needs it), but admins can read and edit it from the dashboard.
create policy "admins can view app settings" on public.app_settings
  for select using (public.is_admin());
create policy "admins can update app settings" on public.app_settings
  for update using (public.is_admin()) with check (public.is_admin());

-- monetag_events and api_usage: no policies for authenticated/anon at all
-- (not even for admins) means RLS blocks all client access by default;
-- these are read/written only by Edge Functions using the service role
-- key, which bypasses RLS entirely. (admin_users and app_settings get
-- admin-only policies above instead, since the dashboard needs to read
-- both.)

-- ============================================================================
-- POINTS: the only way points_balance is allowed to change.
-- ============================================================================
-- Client code (see src/lib/points.ts) never writes to points_balance or
-- points_transactions directly — RLS above blocks it even if it tried.
-- Instead, server-side code (Edge Functions, using the service role key)
-- calls this function via RPC after independently verifying the triggering
-- event (e.g. Monetag's signed server-to-server postback).

create or replace function public.award_points(
  p_user_id uuid,
  p_delta integer,
  p_reason text,
  p_reference_type text default null,
  p_reference_id uuid default null
) returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_new_balance integer;
begin
  update public.users
    set points_balance = points_balance + p_delta,
        updated_at = now()
    where id = p_user_id
    returning points_balance into v_new_balance;

  if v_new_balance is null then
    raise exception 'award_points: user % not found', p_user_id;
  end if;

  insert into public.points_transactions (user_id, delta, balance_after, reason, reference_type, reference_id)
  values (p_user_id, p_delta, v_new_balance, p_reason, p_reference_type, p_reference_id);

  return v_new_balance;
end;
$$;

-- Lock execution down to the service role only — anon/authenticated callers
-- (i.e. the frontend) can never invoke this, even via RPC.
revoke all on function public.award_points(uuid, integer, text, text, uuid) from public, anon, authenticated;
grant execute on function public.award_points(uuid, integer, text, text, uuid) to service_role;

-- ============================================================================
-- Upsert-or-create a user row from verified Telegram profile data.
-- Called by the telegram-auth Edge Function after HMAC verification, using
-- the service role key. Never exposed to anon/authenticated.
-- ============================================================================

create or replace function public.upsert_telegram_user(
  p_telegram_id bigint,
  p_telegram_username text,
  p_first_name text,
  p_last_name text,
  p_photo_url text
) returns public.users
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.users;
begin
  insert into public.users (telegram_id, telegram_username, first_name, last_name, photo_url, last_seen_at)
  values (p_telegram_id, p_telegram_username, p_first_name, p_last_name, p_photo_url, now())
  on conflict (telegram_id) do update set
    telegram_username = excluded.telegram_username,
    first_name = excluded.first_name,
    last_name = excluded.last_name,
    photo_url = excluded.photo_url,
    last_seen_at = now(),
    updated_at = now()
  returning * into v_user;

  return v_user;
end;
$$;

revoke all on function public.upsert_telegram_user(bigint, text, text, text, text) from public, anon, authenticated;
grant execute on function public.upsert_telegram_user(bigint, text, text, text, text) to service_role;

-- ============================================================================
-- DEFAULT SETTINGS
-- ============================================================================

insert into public.app_settings (key, value)
values ('points_per_rewarded_ad', '1'::jsonb)
on conflict (key) do nothing;
