-- DevOptimizeBot seed: 7 categories + 121 tools
BEGIN;

-- categories already in 002; upsert tools
INSERT INTO tools (id, name, slug, category_id, description, enabled) VALUES
(1, 'YouTube Video Title Generator', 'youtube-video-title-generator', 1, 'Generate engaging YouTube video titles', true),
(2, 'YouTube Tag Extractor', 'youtube-tag-extractor', 1, 'Extract tags from any YouTube video', true),
(3, 'YouTube Thumbnail Previewer', 'youtube-thumbnail-previewer', 1, 'Preview how thumbnails look on YouTube', true),
(4, 'YouTube Channel ID Finder', 'youtube-channel-id-finder', 1, 'Find any YouTube channel ID', true),
(5, 'YouTube Description Generator', 'youtube-description-generator', 1, 'Generate optimized video descriptions', true),
(6, 'YouTube Money Calculator', 'youtube-money-calculator', 1, 'Estimate YouTube earnings potential', true),
(7, 'YouTube Embed Code Generator', 'youtube-embed-code-generator', 1, 'Generate YouTube embed codes', true),
(8, 'YouTube Region Restriction Checker', 'youtube-region-restriction-checker', 1, 'Check video region restrictions', true),
(9, 'YouTube Comment Picker', 'youtube-comment-picker', 1, 'Randomly pick comments for giveaways', true),
(10, 'YouTube Live Subscriber Counter', 'youtube-live-subscriber-counter', 1, 'Live subscriber count tracker', true),
(11, 'YouTube Timestamp Link Maker', 'youtube-timestamp-link-maker', 1, 'Create timestamped YouTube links', true),
(12, 'YouTube Search Trend Analyzer', 'youtube-search-trend-analyzer', 1, 'Analyze YouTube search trends', true),
(13, 'YouTube Channel Audit Checklist', 'youtube-channel-audit-checklist', 1, 'Complete channel audit checklist', true),
(14, 'YouTube Shorts Script Timer', 'youtube-shorts-script-timer', 1, 'Time your Shorts scripts', true),
(15, 'YouTube Metadata Viewer', 'youtube-metadata-viewer', 1, 'View full video metadata', true),
(16, 'TikTok Engagement Calculator', 'tiktok-engagement-calculator', 2, 'Calculate TikTok engagement rates', true),
(17, 'TikTok Caption Generator', 'tiktok-caption-generator', 2, 'Generate engaging TikTok captions', true),
(18, 'TikTok Bio Generator', 'tiktok-bio-generator', 2, 'Create optimized TikTok bios', true),
(19, 'TikTok Video Length Splitter', 'tiktok-video-length-splitter', 2, 'Split videos for TikTok limits', true),
(20, 'Pinterest Board Cover Maker', 'pinterest-board-cover-maker', 2, 'Create Pinterest board covers', true),
(21, 'Pinterest Pin Title Optimizer', 'pinterest-pin-title-optimizer', 2, 'Optimize Pinterest pin titles', true),
(22, 'Pinterest Description Builder', 'pinterest-description-builder', 2, 'Build Pinterest descriptions', true),
(23, 'Pinterest Multi-Image Collage Layout', 'pinterest-multi-image-collage-layout', 2, 'Create multi-image collage layouts', true),
(24, 'Robots.txt Generator', 'robots-txt-generator', 3, 'Generate robots.txt files', true),
(25, 'XML Sitemap Generator', 'xml-sitemap-generator', 3, 'Generate XML sitemaps', true),
(26, 'Hreflang Tag Builder', 'hreflang-tag-builder', 3, 'Build hreflang tags', true),
(27, 'HTTP Status Code Checker', 'http-status-code-checker', 3, 'Check HTTP status codes', true),
(28, 'Redirect Chain Auditing Tool', 'redirect-chain-auditing-tool', 3, 'Audit redirect chains', true),
(29, 'Sitemap Validator', 'sitemap-validator', 3, 'Validate XML sitemaps', true),
(30, 'Canonical Tag Checker', 'canonical-tag-checker', 3, 'Check canonical tags', true),
(31, 'Crawl Depth Map Generator', 'crawl-depth-map-generator', 3, 'Map crawl depth of pages', true),
(32, 'Text-to-HTML Ratio Calculator', 'text-to-html-ratio-calculator', 3, 'Calculate text-to-HTML ratio', true),
(33, 'Keyword Density Analyzer', 'keyword-density-analyzer', 3, 'Analyze keyword density', true),
(34, 'SERP Preview Tool', 'serp-preview-tool', 3, 'Preview search engine results', true),
(35, 'Heading Tag Hierarchy Reviewer', 'heading-tag-hierarchy-reviewer', 3, 'Review heading hierarchy', true),
(36, 'Image Alt Text Auditor', 'image-alt-text-auditor', 3, 'Audit image alt texts', true),
(37, 'Meta Tag Generator', 'meta-tag-generator', 3, 'Generate meta tags', true),
(38, 'Schema Markup Generator', 'schema-markup-generator', 3, 'Generate schema markup', true),
(39, 'Rich Snippets Tester', 'rich-snippets-tester', 3, 'Test rich snippets', true),
(40, 'Domain Authority Checker', 'domain-authority-checker', 4, 'Check domain authority', true),
(41, 'Backlink Checker', 'backlink-checker', 4, 'Check backlinks', true),
(42, 'Anchor Text Analyzer', 'anchor-text-analyzer', 4, 'Analyze anchor text', true),
(43, 'Disavow File Generator', 'disavow-file-generator', 4, 'Generate disavow files', true),
(44, 'Page Speed Performance Audit', 'page-speed-performance-audit', 4, 'Audit page speed', true),
(45, 'SSL Certificate Checker', 'ssl-certificate-checker', 4, 'Check SSL certificates', true),
(46, 'Domain Age Checker', 'domain-age-checker', 4, 'Check domain age', true),
(47, 'Domain WHOIS Lookup', 'domain-whois-lookup', 4, 'WHOIS lookup for domains', true),
(48, 'DNS Record Finder', 'dns-record-finder', 4, 'Find DNS records', true),
(49, 'Google Cache Date Checker', 'google-cache-date-checker', 4, 'Check Google cache date', true),
(50, 'JSON Formatter & Validator', 'json-formatter-validator', 5, 'Format and validate JSON', true),
(51, 'JSON to XML Converter', 'json-to-xml-converter', 5, 'Convert JSON to XML', true),
(52, 'XML to JSON Converter', 'xml-to-json-converter', 5, 'Convert XML to JSON', true),
(53, 'Base64 Encoder & Decoder', 'base64-encoder-decoder', 5, 'Encode and decode Base64', true),
(54, 'URL Encoder & Decoder', 'url-encoder-decoder', 5, 'Encode and decode URLs', true),
(55, 'MD5 Hash Generator', 'md5-hash-generator', 5, 'Generate MD5 hashes', true),
(56, 'SHA-256 Generator', 'sha-256-generator', 5, 'Generate SHA-256 hashes', true),
(57, 'Bcrypt Generator', 'bcrypt-generator', 5, 'Generate bcrypt hashes', true),
(58, 'JavaScript Minifier', 'javascript-minifier', 5, 'Minify JavaScript code', true),
(59, 'CSS Minifier', 'css-minifier', 5, 'Minify CSS code', true),
(60, 'HTML Minifier', 'html-minifier', 5, 'Minify HTML code', true),
(61, 'SQL Formatter', 'sql-formatter', 5, 'Format SQL queries', true),
(62, 'Regex Tester', 'regex-tester', 5, 'Test regular expressions', true),
(63, 'JWT Decoder', 'jwt-decoder', 5, 'Decode JWT tokens', true),
(64, 'Cron Expression Generator', 'cron-expression-generator', 5, 'Generate cron expressions', true),
(65, 'YAML to JSON Converter', 'yaml-to-json-converter', 5, 'Convert YAML to JSON', true),
(66, 'JSON to CSV Converter', 'json-to-csv-converter', 5, 'Convert JSON to CSV', true),
(67, 'Mobile-Friendly Tester', 'mobile-friendly-tester', 5, 'Test mobile friendliness', true),
(68, 'Link Extraction Tool', 'link-extraction-tool', 5, 'Extract links from text/HTML', true),
(69, 'QR Code Generator', 'qr-code-generator', 5, 'Generate QR codes', true),
(70, 'SHA-1 Hash Generator', 'sha-1-hash-generator', 5, 'Generate SHA-1 hashes', true),
(71, 'SHA-512 Hash Generator', 'sha-512-hash-generator', 5, 'Generate SHA-512 hashes', true),
(72, 'API Key & Password Generator', 'api-key-password-generator', 5, 'Generate secure API keys and passwords', true),
(73, 'HTTP Security Header Checker', 'http-security-header-checker', 5, 'Check HTTP security headers', true),
(74, 'Security.txt File Generator', 'security-txt-file-generator', 5, 'Generate security.txt files', true),
(75, 'CORS Configuration Generator', 'cors-configuration-generator', 5, 'Generate CORS configurations', true),
(76, 'XSS Input Sanitizer', 'xss-input-sanitizer', 5, 'Sanitize input against XSS', true),
(77, 'SVG Compressor & Optimizer', 'svg-compressor-optimizer', 5, 'Compress and optimize SVGs', true),
(78, 'Gzip & Brotli Savings Calculator', 'gzip-brotli-savings-calculator', 5, 'Calculate compression savings', true),
(79, 'Lazy Load Image Code Generator', 'lazy-load-image-code-generator', 5, 'Generate lazy load image code', true),
(80, 'Critical CSS Generator', 'critical-css-generator', 5, 'Generate critical CSS', true),
(81, '@font-face CSS Generator', 'font-face-css-generator', 5, 'Generate @font-face CSS', true),
(82, 'Browser Cache & Storage Cleaner', 'browser-cache-storage-cleaner', 5, 'Clear browser cache and storage', true),
(83, 'Slug Generator', 'slug-generator', 6, 'Generate URL-friendly slugs', true),
(84, 'Word Counter & Reading Time Estimator', 'word-counter-reading-time-estimator', 6, 'Count words and estimate reading time', true),
(85, 'Case Converter', 'case-converter', 6, 'Convert text case', true),
(86, 'Remove Duplicate Lines', 'remove-duplicate-lines', 6, 'Remove duplicate lines from text', true),
(87, 'Line Counter', 'line-counter', 6, 'Count lines in text', true),
(88, 'Text Diff Checker', 'text-diff-checker', 6, 'Compare two texts', true),
(89, 'Random String Generator', 'random-string-generator', 6, 'Generate random strings', true),
(90, 'Lorem Ipsum Generator', 'lorem-ipsum-generator', 6, 'Generate Lorem Ipsum text', true),
(91, 'Markdown to HTML Converter', 'markdown-to-html-converter', 6, 'Convert Markdown to HTML', true),
(92, 'HTML to Markdown Converter', 'html-to-markdown-converter', 6, 'Convert HTML to Markdown', true),
(93, 'Text Sorter', 'text-sorter', 6, 'Sort lines of text', true),
(94, 'Find and Replace Tool', 'find-and-replace-tool', 6, 'Find and replace text', true),
(95, 'Morse Code Converter', 'morse-code-converter', 6, 'Convert text to Morse code', true),
(96, 'Stripper of HTML Tags', 'stripper-of-html-tags', 6, 'Strip HTML tags from text', true),
(97, 'Word Frequency Counter', 'word-frequency-counter', 6, 'Count word frequency', true),
(98, 'Reverse Text Generator', 'reverse-text-generator', 6, 'Reverse text', true),
(99, 'Whitespace Remover', 'whitespace-remover', 6, 'Remove extra whitespace', true),
(100, 'HEX to RGB Converter', 'hex-to-rgb-converter', 7, 'Convert HEX to RGB', true),
(101, 'RGB to HEX Converter', 'rgb-to-hex-converter', 7, 'Convert RGB to HEX', true),
(102, 'Color Palette Generator', 'color-palette-generator', 7, 'Generate color palettes', true),
(103, 'CSS Gradient Generator', 'css-gradient-generator', 7, 'Generate CSS gradients', true),
(104, 'SVG to PNG Converter', 'svg-to-png-converter', 7, 'Convert SVG to PNG', true),
(105, 'PNG to JPEG Converter', 'png-to-jpeg-converter', 7, 'Convert PNG to JPEG', true),
(106, 'CSS Box Shadow Generator', 'css-box-shadow-generator', 7, 'Generate CSS box shadows', true),
(107, 'Image Aspect Ratio Calculator', 'image-aspect-ratio-calculator', 7, 'Calculate image aspect ratios', true),
(108, 'Favicon Generator', 'favicon-generator', 7, 'Generate favicons', true),
(109, 'Image Resizer', 'image-resizer', 7, 'Resize images', true),
(110, 'CSS Border Radius Generator', 'css-border-radius-generator', 7, 'Generate CSS border radius', true),
(111, 'Color Contrast Checker', 'color-contrast-checker', 7, 'Check color contrast', true),
(112, 'Image Color Picker', 'image-color-picker', 7, 'Pick colors from images', true),
(113, 'Placeholder Image Generator', 'placeholder-image-generator', 7, 'Generate placeholder images', true),
(114, 'Percentage Calculator', 'percentage-calculator', 7, 'Calculate percentages', true),
(115, 'Age Calculator', 'age-calculator', 7, 'Calculate age from birthdate', true),
(116, 'Compound Interest Calculator', 'compound-interest-calculator', 7, 'Calculate compound interest', true),
(117, 'Unix Timestamp Converter', 'unix-timestamp-converter', 7, 'Convert Unix timestamps', true),
(118, 'Date Difference Calculator', 'date-difference-calculator', 7, 'Calculate date differences', true),
(119, 'Password Strength Meter', 'password-strength-meter', 7, 'Check password strength', true),
(120, 'Random Number Picker', 'random-number-picker', 7, 'Pick random numbers', true),
(121, 'Keyword Position Tracker', 'keyword-position-tracker', 7, 'Track keyword positions', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, slug = EXCLUDED.slug, category_id = EXCLUDED.category_id, description = EXCLUDED.description, enabled = EXCLUDED.enabled;

INSERT INTO app_settings (key, value) VALUES
('app_name', '"DevOptimizeBot"'::jsonb),
('tagline', '"One workbench. Every tool you need."'::jsonb),
('points_name', '"DevOptimizeBot Points"'::jsonb),
('expected_tool_count', '121'::jsonb)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();

COMMIT;
