import { useMemo, useState } from 'react'
import ToolShell from '../../components/ToolShell'
import CopyButton from '../../components/CopyButton'

/**
 * A basic optimizer: removes comments, XML declarations, metadata/title/desc
 * elements and collapses whitespace between tags. This does not touch path
 * data precision or merge shapes the way a full tool like SVGO does — those
 * optimizations need real geometry handling.
 */
function optimizeSvg(svg: string): string {
  let out = svg
    .replace(/<\?xml[\s\S]*?\?>/g, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<!DOCTYPE[\s\S]*?>/gi, '')
    .replace(/<metadata[\s\S]*?<\/metadata>/gi, '')
    .replace(/<title[\s\S]*?<\/title>/gi, '')
    .replace(/<desc[\s\S]*?<\/desc>/gi, '')
    .replace(/>\s+</g, '><')
    .replace(/\s{2,}/g, ' ')
    .trim()

  return out
}

const SAMPLE = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by design tool -->
<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100">
  <title>Icon</title>
  <metadata>some editor metadata</metadata>
  <circle cx="50" cy="50" r="40" fill="#FFC531" />
</svg>`

export default function SvgOptimizer() {
  const [input, setInput] = useState(SAMPLE)
  const output = useMemo(() => optimizeSvg(input), [input])
  const savings = input.length ? Math.round((1 - output.length / input.length) * 100) : 0

  return (
    <ToolShell title="SVG Compressor & Optimizer" description="Strip comments, metadata and excess whitespace from an SVG. A basic pass, not full path optimization.">
      <textarea value={input} onChange={(e) => setInput(e.target.value)} rows={8} className="field font-mono text-sm" />

      <div className="mt-3 flex items-center justify-between">
        <p className="text-xs text-white/40">
          {input.length} → {output.length} bytes ({savings}% smaller)
        </p>
        <CopyButton text={output} />
      </div>
      <textarea value={output} readOnly rows={5} className="field mt-1 font-mono text-sm" />
    </ToolShell>
  )
}
